### ISSUE TITLE
add video/gif demo to README

### ISSUE THREAD

**Issue by b0o** [lthms/spatial-sway#18]
Hey, this looks like a cool project! Some feedback: I think I get the gist of what this project does, but it's a bit hard to understand the README. I think a video demo would help a lot to demonstrate the project, and would make it easier for people to know if this tool would benefit their workflow. Thanks!

**Comment by lthms** [comment]
Thanks! I will see to add the one that I made a few months back, that you can find [here](https://soap.coffee/~lthms/posts/SpatialShell6.html) if you want to confirm your intuition.

**Comment by b0o** [comment]
Hey, yes I think that video would be great in the README.

**Comment by lthms** [comment]
Done! Took me more time that it should have, but better late than never? :sweat_smile: 
Thanks for the suggestion
